### ISSUE TITLE
arXiv link generator in quantum.bst not working properly

### ISSUE THREAD

**Issue by leologist** [cgogolin/quantum-journal#139] opened 2022-07-02 01:59 UTC
There is an issue with the current version of the bib style file: quantum.bst.

I find that it does not properly convert the eprint field of certain article items in my *.bib library, and had to manually modify the *.bbl file generated.  This was under \usepackage[numbers]{natbib}.

For example, it will translate arXiv:1803.11173 into https://arxiv.org/abs/1803.01117.

**Comment by cgogolin** [comment] 2022-10-15 12:55
@dwierichs do you have an idea what could be causing this?

**Comment by dwierichs** [comment] 2022-10-15 15:19
Certainly will be able to figure this out. @leologist Thank you for pointing this out. Will try to get to fix this soon, together with some other minor fixes!

**Comment by dwierichs** [comment] 2022-10-16 17:58
The bug is caused by me not being able to count in the natural numbers... Set up a fix: #145 

This bug will affect all bibliography entries with `eprint={arxiv:1234.12345}` or `eprint={arxiv1234.12345}` (i.e. with or without colon, ignoring capitalization), but not for example those that have `eprint={1234.12345}` or `eprint={somethingelse:1234.12345}`.

**Comment by cgogolin** [comment] 2022-10-16 18:25
Thanks for the quick fix! The no merged #145 will be shortly published as part of v6.1.

**Closed as completed by cgogolin** 2022-10-16 18:25 UTC
